// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw39Rnfq2RdJFi-SjxfpLy4JbPlP0Kc_k',
    appId: '1:1069777859272:web:d849b0c3ff91083d54abfd',
    messagingSenderId: '1069777859272',
    projectId: 'fir-employee-crud',
    authDomain: 'fir-employee-crud.firebaseapp.com',
    storageBucket: 'fir-employee-crud.appspot.com',
    measurementId: 'G-J2T4BJLNHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOo8gJ0f3Fj4LkW6_hAIxgbCyCwmocow',
    appId: '1:1069777859272:android:43e84ed70aa6049654abfd',
    messagingSenderId: '1069777859272',
    projectId: 'fir-employee-crud',
    storageBucket: 'fir-employee-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbz3XNc9U8bJLkLL3iDGBXRdwwnTU89k',
    appId: '1:1069777859272:ios:4a648129b2d28a7d54abfd',
    messagingSenderId: '1069777859272',
    projectId: 'fir-employee-crud',
    storageBucket: 'fir-employee-crud.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbz3XNc9U8bJLkLL3iDGBXRdwwnTU89k',
    appId: '1:1069777859272:ios:4a648129b2d28a7d54abfd',
    messagingSenderId: '1069777859272',
    projectId: 'fir-employee-crud',
    storageBucket: 'fir-employee-crud.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw39Rnfq2RdJFi-SjxfpLy4JbPlP0Kc_k',
    appId: '1:1069777859272:web:8172cb45c2be21f354abfd',
    messagingSenderId: '1069777859272',
    projectId: 'fir-employee-crud',
    authDomain: 'fir-employee-crud.firebaseapp.com',
    storageBucket: 'fir-employee-crud.appspot.com',
    measurementId: 'G-LFPP7XPTLB',
  );
}
